import React, { useState } from 'react';
import { Box, Typography, Button, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Container, Card, Divider, Chip } from '@mui/material';
import CompareArrowsIcon from '@mui/icons-material/CompareArrows';
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";
import Footer from "../components/Footer";

const PaperComparison = () => {
  const [comparing, setComparing] = useState(false);
  const [results, setResults] = useState(null);

  const handleCompare = () => {
    setComparing(true);
    // Simulate comparison logic
    setTimeout(() => {
      setComparing(false);
      setResults([
        { metric: 'Core Methodology', paper1: 'Transformer-based', paper2: 'CNN-based', paper3: 'Hybrid' },
        { metric: 'Accuracy (Top-1)', paper1: '94.2%', paper2: '91.8%', paper3: '95.1%' },
        { metric: 'Inference Speed', paper1: 'Fast', paper2: 'Very Fast', paper3: 'Medium' },
        { metric: 'Dataset Size', paper1: '1.2B tokens', paper2: '800M tokens', paper3: '2.5B tokens' },
        { metric: 'Hardware Requirements', paper1: 'V100 GPU', paper2: 'P100 GPU', paper3: 'A100 GPU' },
      ]);
    }, 2000);
  };

  return (
    <Box sx={{ minHeight: "100vh", display: "flex", flexDirection: "column" }}>
      <Navbar />
      <Box sx={{ display: "flex", flex: 1, mt: "72px" }}>
        <Sidebar />
        <Box
          component="main"
          sx={{
            flexGrow: 1,
            p: { xs: 2, md: 4, lg: 6 },
            ml: { lg: "280px", xs: 0 },
            background: "#F8FAFF",
            minHeight: "calc(100vh - 72px)"
          }}
        >
          <Container maxWidth="lg">
            <Box sx={{ display: "flex", alignItems: "center", gap: 2, mb: 1 }}>
              <CompareArrowsIcon sx={{ color: "#101828" }} />
              <Typography variant="h4" sx={{ fontWeight: 700 }}>Multi-Paper Comparison</Typography>
            </Box>
            <Typography variant="body1" sx={{ mb: 4, color: "#667085" }}>
              Compare multiple research papers across key metrics and methodologies.
            </Typography>

            <Card sx={{ p: 4, mb: 6, textAlign: "center" }}>
              <Typography variant="h6" sx={{ mb: 2 }}>Ready to compare your selected papers?</Typography>
              <Typography variant="body2" sx={{ mb: 4, color: "#667085" }}>You have selected 3 papers from your library.</Typography>
              <Button
                variant="contained"
                onClick={handleCompare}
                disabled={comparing}
                sx={{ 
                  bgcolor: "#101828", 
                  "&:hover": { bgcolor: "#1D2939" }, 
                  px: 6, 
                  py: 1.5,
                  borderRadius: "30px"
                }}
              >
                {comparing ? 'Generating Comparison...' : 'Start Comparison Matrix'}
              </Button>
            </Card>

            {results && (
              <Box>
                <Typography variant="h6" sx={{ mb: 3, fontWeight: 700 }}>Comparison Matrix</Typography>
                <TableContainer component={Card} sx={{ boxShadow: "none", border: "1px solid #EAECF0" }}>
                  <Table sx={{ minWidth: 650 }}>
                    <TableHead sx={{ bgcolor: "#F9FAFB" }}>
                      <TableRow>
                        <TableCell sx={{ fontWeight: 700, color: "#475467" }}>Metric</TableCell>
                        <TableCell sx={{ fontWeight: 700, color: "#101828" }}>Paper A (Primary)</TableCell>
                        <TableCell sx={{ fontWeight: 700, color: "#101828" }}>Paper B</TableCell>
                        <TableCell sx={{ fontWeight: 700, color: "#101828" }}>Paper C</TableCell>
                      </TableRow>
                    </TableHead>
                    <TableBody>
                      {results.map((row, index) => (
                        <TableRow key={index} sx={{ "&:last-child td, &:last-child th": { border: 0 } }}>
                          <TableCell component="th" scope="row" sx={{ fontWeight: 600, color: "#475467", bgcolor: "#F9FAFB" }}>
                            {row.metric}
                          </TableCell>
                          <TableCell sx={{ color: "#101828" }}>{row.paper1}</TableCell>
                          <TableCell sx={{ color: "#101828" }}>{row.paper2}</TableCell>
                          <TableCell sx={{ color: "#101828" }}>{row.paper3}</TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </TableContainer>
                <Box sx={{ mt: 4, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                  <Typography variant="body2" color="text.secondary">Generated by AI Researcher • Mar 2024</Typography>
                  <Button variant="outlined" sx={{ borderColor: "#D0D5DD", color: "#344054" }}>Export to Excel</Button>
                </Box>
              </Box>
            )}
          </Container>
        </Box>
      </Box>
      <Footer />
    </Box>
  );
};

export default PaperComparison;
